CREATE SCHEMA IF NOT EXISTS "bci-users";

CREATE TABLE IF NOT EXISTS "BCI_USER" (
    "IS_ACTIVE" BOOLEAN DEFAULT true ,
    "CREATED" TIMESTAMP NOT NULL,
    "LAST_LOGIN" TIMESTAMP,
    "MODIFIED" TIMESTAMP,
    "ID" CHARACTER VARYING(255) NOT NULL,
    "EMAIL" CHARACTER VARYING(255) NOT NULL,
    "NAME" CHARACTER VARYING(255) NOT NULL,
    "PASSWORD" CHARACTER VARYING(255) NOT NULL,
    "TOKEN" CHARACTER VARYING(255) NOT NULL,
    PRIMARY KEY("ID"),
    UNIQUE("ID")
);

CREATE TABLE IF NOT EXISTS "PHONE" (
  "ID" BIGINT,
  "NUMBER" CHARACTER VARYING(255) NOT NULL,
  "CITY_CODE" CHARACTER VARYING(255) NOT NULL,
  "COUNTRY_CODE" CHARACTER VARYING(255) NOT NULL,
  PRIMARY KEY("ID"),
  UNIQUE("ID")
);

CREATE TABLE IF NOT EXISTS "BCI_USER_PHONES" (
  "PHONES_ID" BIGINT,
  "USER_ID" CHARACTER VARYING(255) NOT NULL,
  PRIMARY KEY(USER_ID, PHONES_ID),
  FOREIGN KEY (PHONES_ID) references "PHONE"(ID),
  FOREIGN KEY (USER_ID) references "BCI_USER"(ID)
);

